name: iostest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # contacts_service: ^0.4.6
  duration: ^2.0.0
  google_fonts: any
  intl: ^0.17.0
  # cloud_firestore: ^1.0.3
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1 
  firebase_messaging: ^9.1.0
  # email_auth:
  # pinput: ^0.2.6
  # firebase_storage: 

  # flutter_facebook_login: 
  # flutter_bloc: ^0.13.0
  # bloc: ^0.13.0
  # equatable: ^0.2.3
  # meta: ^1.1.6
  # font_awesome_flutter: ^8.4.0
  # dashed_container: ^1.0.1
  # shared_preferences: any
  # carousel_slider: ^2.3.1
  # fluttertoast:
  # http:
  # dio: 3.0.9
  # expandable: ^3.0.0+1
  # clippy_flutter: ^1.1.0
  # provider: ^2.0.0
  # hidden_drawer_menu: ^1.1.2
  # simple_animations: ^1.3.3
  # razorpay_flutter: 1.1.0

  # package_info: ^0.4.0+6
  # url_launcher: ^5.1.6
  # firebase_remote_config: ^0.6.0
  # r_upgrade:
  # permission_handler: ^3.2.2
  # rflutter_alert: ^1.0.3
  # curved_navigation_bar: ^0.3.1
  # bottom_navy_bar: ^5.2.2
  # share: ^0.6.1+1
  # modal_progress_hud: ^0.1.3
  # image_picker: 0.6.0+2
  # image_cropper: ^1.0.2
  # folding_cell: "^0.1.2"
  # scratcher: ^1.3.0
  # progress_dialog: ^1.2.0
  # sticky_headers: "^0.1.8"
  # flutter_launcher_icons: ^0.7.4
  # stopper: ^1.0.1
  # solid_bottom_sheet: ^0.1.9
  # expandable_bottom_sheet: ^0.2.1+1
  # flare_flutter: ^2.0.1
  # date_format: ^1.0.8
  # confetti: ^0.3.0
  # liquid_progress_indicator: ^0.3.2
  # autocomplete_textfield: ^1.7.3
  # flutter_svg: ^0.18.0
  # get: ^3.15.0
  # diffutil_dart: ^1.0.2
  # cached_network_image:
  # change_app_package_name: ^0.1.2
  # ntp: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
